@hostname = http://localhost:4000

### Get data
get {{hostname}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzZXIiLCJhZG1pblJvbGUiOmZhbHNlLCJpYXQiOjE2NTI4MDgzMjAsImV4cCI6MTY1Mjg5NDcyMH0.7sC2kywYitiKbQfIWn3fJMaN5Y6eFChinjwjRIwTefQ

### Get test data
get {{hostname}}/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzZXIiLCJyb2xlIjoidXNlciIsImlhdCI6MTY1Mjc3MTY0MiwiZXhwIjoxNjUyODU4MDQyfQ.M766hEoQ2SolIO4wISfIUmZWn85yqzFVmwXsm2BLX7E

### Login
post {{hostname}}/login
Content-Type: application/json

{
    "userName": "user",
    "password": "user"
}

### Logout
post {{hostname}}/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzZXIiLCJyb2xlIjoidXNlciIsImlhdCI6MTY1Mjc3NDA4NywiZXhwIjoxNjUyODYwNDg3fQ.Uroa2IeUmZL86KXQ810qeC0n0yPYQP8IUmg2MOgcl14; Max-Age=86400; Path=/; Expires=Wed, 18 May 2022 07:54:47 GMT
